# Generated by Django 5.1.1 on 2024-09-27 17:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Projects', '0007_rename_departamento_proyectos_departamento_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feed_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('info', models.CharField(max_length=255, unique=True)),
                ('proyecto_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.proyectos')),
            ],
        ),
    ]
