# Generated by Django 5.1.1 on 2024-09-27 15:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('departamentos_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departments.direccion')),
            ],
        ),
    ]
