# Generated by Django 5.1.1 on 2026-05-21 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0002_departamentos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='departamentos',
            name='jefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos_dirigidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='direccion',
            name='jefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direcciones_dirigidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
