# Generated by Django 5.1.1 on 2026-05-08 07:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Projects', '0009_remove_proyectos_project_photo_projectimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCambios',
            fields=[
                ('historial_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('creacion', 'Creación'), ('edicion_tarea', 'Edición de tarea'), ('edicion_proyecto', 'Edición de proyecto'), ('cambio_estado_tarea', 'Cambio de estado de tarea'), ('cambio_estado_proyecto', 'Cambio de estado de proyecto'), ('ampliacion_plazo', 'Ampliación de plazo'), ('reprogramacion', 'Reprogramación'), ('cancelacion', 'Cancelación'), ('solicitud_presupuesto', 'Solicitud de presupuesto adicional'), ('asignacion', 'Asignación de tarea')], max_length=50)),
                ('tarea_ID', models.CharField(blank=True, default='', max_length=36)),
                ('razon', models.TextField(blank=True, default='')),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('proyecto_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='Projects.proyectos')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
