# Generated by Django 5.1.1 on 2024-09-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='descripcion',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
