# Generated by Django 5.1.1 on 2026-05-05 00:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_tareas_task_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareas',
            name='task_photo',
        ),
        migrations.CreateModel(
            name='TaskImage',
            fields=[
                ('imagen_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('public_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Task.tareas')),
            ],
        ),
    ]
