# Generated by Django 5.1.1 on 2026-05-21 08:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0010_ajustepresupuesto_delegacionsupervision_and_more'),
        ('Task', '0005_tareas_asignado_a_alter_tareas_descripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='costo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='tareas',
            index=models.Index(fields=['fecha_entrega'], name='Task_tareas_fecha_e_b3d803_idx'),
        ),
        migrations.AddIndex(
            model_name='tareas',
            index=models.Index(fields=['asignado_a', 'fecha_entrega'], name='Task_tareas_asignad_2c7b97_idx'),
        ),
        migrations.AddIndex(
            model_name='tareas',
            index=models.Index(fields=['proyecto_ID', 'estado_ID'], name='Task_tareas_proyect_b8d65c_idx'),
        ),
    ]
