# Generated by Django 5.1.1 on 2024-09-27 15:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0002_departamentos'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('cedula', models.IntegerField(unique=True)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('puesto', models.CharField(max_length=25)),
                ('departamento_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departments.departamentos')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.roles')),
            ],
        ),
    ]
