# Generated by Django 5.1.1 on 2024-09-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_users_managers_remove_users_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_authenticated',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
