# Generated by Django 5.1.1 on 2024-10-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_remove_users_is_active_remove_users_is_anonymous_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
    ]
