# Generated by Django 5.1.1 on 2024-10-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_users_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_photo',
            field=models.TextField(null=True),
        ),
    ]
