# Generated by Django 5.1.1 on 2026-05-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_alter_users_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roles',
            name='puede_delegar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roles',
            name='puede_recibir_delegacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roles',
            name='puede_ver_todo',
            field=models.BooleanField(default=False, help_text='Si es True, ve todos los proyectos sin importar si es dueño/jefe/delegado.'),
        ),
        migrations.AddField(
            model_name='users',
            name='onboarding_completado',
            field=models.BooleanField(default=False),
        ),
    ]
