# Generated by Django 5.1.1 on 2026-05-21 08:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('notificacion_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('vencimiento_proyecto', 'Vencimiento de proyecto'), ('vencimiento_tarea', 'Vencimiento de tarea'), ('cambio_estado', 'Cambio de estado'), ('asignacion', 'Asignación'), ('delegacion', 'Delegación de supervisión'), ('ajuste_presupuesto', 'Ajuste de presupuesto'), ('comentario', 'Nuevo comentario'), ('general', 'General')], default='general', max_length=30)),
                ('titulo', models.CharField(max_length=120)),
                ('mensaje', models.TextField()),
                ('link', models.CharField(blank=True, default='', max_length=255)),
                ('leida', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clave_dedupe', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usuario', 'leida'], name='Notificatio_usuario_4222c5_idx'), models.Index(fields=['usuario', 'created_at'], name='Notificatio_usuario_fc3558_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('clave_dedupe', ''), _negated=True), fields=('usuario', 'clave_dedupe'), name='notif_dedupe_por_usuario')],
            },
        ),
    ]
