# Generated by Django 5.1.1 on 2024-09-27 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_proyectos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos_tipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.proyectos')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.tipos')),
            ],
        ),
    ]
