# Generated by Django 5.1.1 on 2024-09-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_proyectos_tipos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='descripcion',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
