# Generated by Django 5.1.1 on 2024-09-27 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0006_alter_proyectos_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyectos',
            old_name='departamento',
            new_name='departamento_ID',
        ),
        migrations.RenameField(
            model_name='proyectos',
            old_name='estado',
            new_name='estado_ID',
        ),
        migrations.RenameField(
            model_name='proyectos',
            old_name='prioridad',
            new_name='prioridad_ID',
        ),
        migrations.RenameField(
            model_name='proyectos',
            old_name='user',
            new_name='user_ID',
        ),
    ]
