# Generated by Django 5.1.1 on 2024-11-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0007_rename_departamento_proyectos_departamento_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='project_photo',
            field=models.TextField(null=True),
        ),
    ]
