# Generated by Django 5.1.1 on 2026-05-21 08:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0003_departamentos_jefe_direccion_jefe'),
        ('Projects', '0009_remove_proyectos_project_photo_projectimage'),
        ('Task', '0005_tareas_asignado_a_alter_tareas_descripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AjustePresupuesto',
            fields=[
                ('ajuste_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('aumento', 'Aumento'), ('rebajo', 'Rebajo')], max_length=10)),
                ('monto', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('motivo', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DelegacionSupervision',
            fields=[
                ('delegacion_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('puede_editar', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'ordering': ['orden', 'name']},
        ),
        migrations.AlterModelOptions(
            name='prioridad',
            options={'ordering': ['orden', 'name']},
        ),
        migrations.AddField(
            model_name='estado',
            name='color',
            field=models.CharField(default='#64748b', max_length=7),
        ),
        migrations.AddField(
            model_name='estado',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estado',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prioridad',
            name='color',
            field=models.CharField(default='#64748b', max_length=7),
        ),
        migrations.AddField(
            model_name='prioridad',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prioridad',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='es_publico',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='proyectos',
            index=models.Index(fields=['fecha_entrega'], name='Projects_pr_fecha_e_c0ccf3_idx'),
        ),
        migrations.AddIndex(
            model_name='proyectos',
            index=models.Index(fields=['user_ID', 'fecha_entrega'], name='Projects_pr_user_ID_beca55_idx'),
        ),
        migrations.AddIndex(
            model_name='proyectos',
            index=models.Index(fields=['departamento_ID', 'estado_ID'], name='Projects_pr_departa_3f7be9_idx'),
        ),
        migrations.AddIndex(
            model_name='proyectos',
            index=models.Index(fields=['es_publico'], name='Projects_pr_es_publ_a50539_idx'),
        ),
        migrations.AddField(
            model_name='ajustepresupuesto',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ajustepresupuesto',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_presupuesto', to='Projects.proyectos'),
        ),
        migrations.AddField(
            model_name='ajustepresupuesto',
            name='tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_presupuesto', to='Task.tareas'),
        ),
        migrations.AddField(
            model_name='ajustepresupuesto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delegacionsupervision',
            name='otorgado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegaciones_otorgadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delegacionsupervision',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegaciones', to='Projects.proyectos'),
        ),
        migrations.AddField(
            model_name='delegacionsupervision',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegaciones_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='ajustepresupuesto',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='ajuste_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='ajustepresupuesto',
            constraint=models.CheckConstraint(condition=models.Q(('proyecto__isnull', False), ('tarea__isnull', False), _connector='OR'), name='ajuste_requiere_proyecto_o_tarea'),
        ),
        migrations.AddIndex(
            model_name='delegacionsupervision',
            index=models.Index(fields=['supervisor', 'activa'], name='Projects_de_supervi_5b797a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='delegacionsupervision',
            unique_together={('proyecto', 'supervisor')},
        ),
    ]
